title: audio content analysis --- music information retrieval tasks and applications
description: Companion website for the book "An Introduction to Audio Content Analysis"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman